---
exclude:
  - 'bower_components/**/*.css'
  - 'dist/*.css'
  - 'dist/*.scss'
  - 'node_modules/**/*'
  - 'vendor/**/*'
# TODO FIXME: Delete the following lines
linters:
  Comment:
    enabled: false
  DeclarationOrder:
    enabled: false
  DuplicateProperty:
    enabled: false
  ElsePlacement:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  HexLength:
    enabled: false
  HexNotation:
    enabled: false
  Indentation:
    enabled: false
  LeadingZero:
    enabled: false
  NameFormat:
    enabled: false
  NestingDepth:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  PropertySortOrder:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: false
  SpaceAfterComma:
    enabled: false
  SpaceBetweenParens:
    enabled: false
  StringQuotes:
    enabled: false
  UnnecessaryParentReference:
    enabled: false
  VendorPrefixes:
    enabled: false
  ZeroUnit:
    enabled: false
  PseudoElement:
    enabled: false
  ColorVariable:
    enabled: false
  SpaceAroundOperator:
    enabled: false
  ColorVariable:
    enabled: false
