version: 2

commands:
  install_node_dependencies:
    description: "Install Node.js dependencies"
    steps:
      - checkout
      - run: npm config set registry https://fundingcircle.jfrog.io/fundingcircle/api/npm/npm/
      - run: curl https://$BUNDLE_FUNDINGCIRCLE__JFROG__IO@fundingcircle.jfrog.io/fundingcircle/api/npm/auth >> .npmrc
      - run: npm config fix
      - run: npm ci
    parameters:
      node_env:
        type: string
        default: '18'
  install_ruby_dependencies:
    description: "Install Ruby dependencies"
    steps:
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
  run_tests:
    description: "Run tests"
    steps:
      - run: bundle exec rake --trace

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.0-node
    steps:
      - install_node_dependencies
      - install_ruby_dependencies
      - run_tests

workflows:
  version: 2
  ci:
    jobs:
      - build:
          context: org-global
