version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run:
          name: Install Node.js dependencies
          command: npm install
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - run:
          name: Run tests
          command: bundle exec rake --trace
